REM   Script: Activity08
REM   aggregate operations using GROUP BY

select CUSTOMER_ID,MAX(PURCHASE_AMOUNT) As "Max Amount"  from orders GROUP BY CUSTOMER_ID;

select SALESMAN_ID,ORDER_DATE,MAX(PURCHASE_AMOUNT) As "Max Amount" from orders where ORDER_DATE=TO_DATE('2012/08/17', 'YYYY/MM/DD') GROUP BY SALESMAN_ID,ORDER_DATE;

select CUSTOMER_ID,ORDER_DATE,MAX(PURCHASE_AMOUNT) As "Max Amount" from orders GROUP BY CUSTOMER_ID,ORDER_DATE HAVING MAX(PURCHASE_AMOUNT) IN (2030, 3450, 5760, 6000);

